version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/client/src
    networks:
      - app-network
    tty: true
    
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/server
    networks:
      - app-network
      


